[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=gunicorn -b 0.0.0.0:8000 "mobsf.MobSF.wsgi:application"
    --workers=1
    --threads=10
    --timeout=3600
    --worker-tmp-dir=/tmp
    --log-level=warning
    --log-file=-
    --access-logfile=-
    --error-logfile=-
    --capture-output
directory=/home/mobsf/Mobile-Security-Framework-MobSF
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES"

[program:queue_worker]
command=python3 manage.py queue_worker
directory=/home/mobsf/Mobile-Security-Framework-MobSF
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
