[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=gunicorn -b 0.0.0.0:8000 "mobsf.MobSF.wsgi:application"
    --workers=1
    --threads=10
    --timeout=3600
    --worker-tmp-dir=/tmp
    --log-level=warning
    --log-file=-
    --access-logfile=-
    --error-logfile=-
    --capture-output
directory=/home/mobsf/Mobile-Security-Framework-MobSF
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES",
    NODE_ENV="%(ENV_NODE_ENV)s",
    VALKEY_HOST="%(ENV_VALKEY_HOST)s",
    VALKEY_PORT="%(ENV_VALKEY_PORT)s",
    VALKEY_USERNAME="%(ENV_VALKEY_USERNAME)s",
    VALKEY_PASSWORD="%(ENV_VALKEY_PASSWORD)s",
    MEMORYDB_CLUSTER_NAME="%(ENV_MEMORYDB_CLUSTER_NAME)s",
    AWS_REGION="%(ENV_AWS_REGION)s",
    QUEUE_INPUT="%(ENV_QUEUE_INPUT)s",
    QUEUE_OUTPUT="%(ENV_QUEUE_OUTPUT)s",
    QUEUE_ERRORS="%(ENV_QUEUE_ERRORS)s",
    MOBSF_API_KEY="%(ENV_MOBSF_API_KEY)s",
    AWS_BUCKET_NAME_PRIVATE="%(ENV_AWS_BUCKET_NAME_PRIVATE)s"

[program:queue_worker]
command=python3 manage.py queue_worker
directory=/home/mobsf/Mobile-Security-Framework-MobSF
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
environment=
    NODE_ENV="%(ENV_NODE_ENV)s",
    VALKEY_HOST="%(ENV_VALKEY_HOST)s",
    VALKEY_PORT="%(ENV_VALKEY_PORT)s",
    VALKEY_USERNAME="%(ENV_VALKEY_USERNAME)s",
    VALKEY_PASSWORD="%(ENV_VALKEY_PASSWORD)s",
    MEMORYDB_CLUSTER_NAME="%(ENV_MEMORYDB_CLUSTER_NAME)s",
    AWS_REGION="%(ENV_AWS_REGION)s",
    QUEUE_INPUT="%(ENV_QUEUE_INPUT)s",
    QUEUE_OUTPUT="%(ENV_QUEUE_OUTPUT)s",
    QUEUE_ERRORS="%(ENV_QUEUE_ERRORS)s",
    MOBSF_API_KEY="%(ENV_MOBSF_API_KEY)s",
    AWS_BUCKET_NAME_PRIVATE="%(ENV_AWS_BUCKET_NAME_PRIVATE)s"
